package com.finq.enums;

public enum PermissionCode {
    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    ACCOUNT_READ,
    ACCOUNT_CREATE,
    ACCOUNT_FREEZE,
    ACCOUNT_UPDATE,
    ACCOUNT_DELETE,
    ACCOUNT_UNFREEZE,

    TRANSACTION_READ,
    TRANSACTION_CREATE,
    TRANSACTION_APPROVE,
    TRANSACTION_REJECT,

    KYC_READ,
    KYC_REJECT,
    KYC_APPROVE,

    ADMIN_READ,
    ADMIN_CREATE,
    ADMIN_UPDATE,
    ADMIN_DELETE,

    SYSTEM_CONFIG,
    AUDIT_READ,
    REPORT_GENERATE
}
